import os
import re

# Ensure directory exists
os.makedirs('en', exist_ok=True)

with open('seoraksan-playbook.html', 'r', encoding='utf-8') as f:
    html = f.read()

# 1. Update lang attribute and head meta tags
html = html.replace('<html data-theme="dark" lang="ko">', '<html data-theme="dark" lang="en">')
html = html.replace('<html lang="ko" data-theme="dark">', '<html data-theme="dark" lang="en">')
html = html.replace('<title>설악산 등산 플레이북</title>', '<title>Seoraksan Hiking Playbook</title>')

desc_ko = '<meta content="설악산 국립공원의 3가지 핵심 등산 코스(초급 울산바위 코스, 중급 오색 대청봉 왕복 코스, 고급 공룡능선 종주 코스) 안내 및 상세 등산 지도, 대피소 예약 정보 플레이북" name="description"/>'
desc_en = '<meta content="Seoraksan National Park hiking playbook. Complete guide to the 3 main courses (Beginner Ulsanbawi Course, Intermediate Osaek-Daecheongbong Course, and Advanced Inner-Outer Traverse Course), detailed interactive maps, shelter reservations, and safety tips." name="description"/>'
html = html.replace(desc_ko, desc_en)

# 2. Add Hreflang alternates
hreflang_orig = """<link rel="alternate" hreflang="ko" href="seoraksan-playbook.html">
<link rel="alternate" hreflang="en" href="en/seoraksan-playbook.html">
<link rel="alternate" hreflang="x-default" href="seoraksan-playbook.html">"""

hreflang_en = """<link rel="alternate" hreflang="ko" href="../seoraksan-playbook.html">
<link rel="alternate" hreflang="en" href="seoraksan-playbook.html">
<link rel="alternate" hreflang="x-default" href="../seoraksan-playbook.html">"""

html = html.replace(hreflang_orig, hreflang_en)

# 3. Update asset paths
html = html.replace('src="assets/', 'src="../assets/')
html = html.replace('href="assets/', 'href="../assets/')
html = html.replace('poster="assets/', 'poster="../assets/')
html = html.replace('use href="assets/', 'use href="../assets/')
html = html.replace('srcset="assets/', 'srcset="../assets/')
html = html.replace('url(\'assets/', 'url(\'../assets/')
html = html.replace('url("assets/', 'url("../assets/')

# 4. Header translation
html = html.replace('설악산 플레이북 로고', 'Seoraksan Playbook Logo')
html = html.replace('<span class="logo-text">설악산 플레이북</span>', '<span class="logo-text">Seoraksan Playbook</span>')

# Lang toggle active class swap
toggle_ko_active = """<div class="lang-toggle">
<button class="lang-btn active" onclick="changeLanguage('ko')" aria-label="한국어" aria-pressed="true">KO</button>
<button class="lang-btn" onclick="changeLanguage('en')" aria-label="English" aria-pressed="false">EN</button>
</div>"""

toggle_en_active = """<div class="lang-toggle">
<button class="lang-btn" onclick="changeLanguage('ko')" aria-label="Korean" aria-pressed="false">KO</button>
<button class="lang-btn active" onclick="changeLanguage('en')" aria-label="English" aria-pressed="true">EN</button>
</div>"""

html = html.replace(toggle_ko_active, toggle_en_active)
html = html.replace('aria-label="다크모드 전환"', 'aria-label="Toggle Dark Mode"')

# 5. Hero section translation
html = html.replace('배경영상: 설악산 대청봉의 기암괴석과 운해 (AI 생성)', 'Background video: Majestic granite peaks and sea of clouds at Seoraksan Daecheongbong (AI generated)')
html = html.replace('Ambient loop generated by Gemini', 'Ambient loop generated by Gemini')
html = html.replace(
    '<h1 style="color: var(--hero-text); font-family: var(--font-display); font-size: var(--text-2xl); font-weight: 800; line-height: 1.15; margin-bottom: var(--space-4);">설악산 등산 플레이북</h1>',
    '<h1 style="color: var(--hero-text); font-family: var(--font-display); font-size: var(--text-2xl); font-weight: 800; line-height: 1.15; margin-bottom: var(--space-4);">Seoraksan Hiking Playbook</h1>'
)
html = html.replace(
    '설악산 국립공원(대청봉 1,708m)은 대한민국 백두대간의 척추이자, 수려한 암릉과 깊은 계곡이 자아내는 웅장한 대자연으로 등산가들에게 가장 사랑받는 명산입니다.',
    'Seoraksan National Park (Daecheongbong Peak, 1,708m) is the spine of South Korea\'s Baekdudaegan ridge, widely beloved by hikers for its dramatic granite ridges, deep valleys, and majestic alpine scenery.'
)

# Course Tab buttons
html = html.replace('🟢 초급 코스 (울산바위)', '🟢 Beginner Course (Ulsanbawi)')
html = html.replace('🟠 중급 코스 (오색~대청봉)', '🟠 Intermediate Course (Osaek~Daecheongbong)')
html = html.replace('🔴 고급 코스 (백담사~대청봉~소공원)', '🔴 Advanced Course (Traverse)')

# Stats Labels
html = html.replace('<strong>총 거리</strong>', '<strong>Total Distance</strong>')
html = html.replace('<strong>소요시간</strong>', '<strong>Duration</strong>')
html = html.replace('<strong>최고지점</strong>', '<strong>Peak Elevation</strong>')
html = html.replace('<strong>누적상승</strong>', '<strong>Elevation Gain</strong>')
html = html.replace('<strong>칼로리</strong>', '<strong>Calories</strong>')
html = html.replace('<strong>난이도</strong>', '<strong>Difficulty</strong>')

html = html.replace('<span>초급</span>', '<span>Beginner</span>')
html = html.replace('<span>중급</span>', '<span>Intermediate</span>')
html = html.replace('<span>고급</span>', '<span>Advanced</span>')

html = html.replace('왕복', 'Round Trip')
html = html.replace('종주', 'Traverse')

# 6. Translate Course content - Beginner Course (Ulsanbawi)
html = html.replace('📊 고도 프로파일 — 울산바위 코스', '📊 Elevation Profile — Ulsanbawi Course')
html = html.replace('코스 특징</h2>', 'Course Highlights</h2>')
html = html.replace('설악산의 가장 대표적인 명소인 흔들바위와 웅장한 울산바위를 오르는 코스입니다.', 'This course ascends to Heondeulbawi (spherical rock) and the grand granite peaks of Ulsanbawi, the most iconic landmarks of Seoraksan.')
html = html.replace('초반 3km는 경사가 완만하여 걷기 좋으나, 마지막 0.6km 구간은 철제 계단이 가파르게 이어져 체력 안배가 필요합니다.', 'The first 3km is a gentle, pleasant walk, but the final 0.6km is a steep, continuous flight of iron stairs requiring careful pacing.')
html = html.replace('정상 전망대에서는 동해바다와 미시령, 외설악의 기암괴석이 어우러진 대파노라마를 감상할 수 있습니다.', 'From the summit observatory, enjoy a grand panorama combining the East Sea, Misiryeong Pass, and the rocky peaks of Outer Seorak.')

# Cards
html = html.replace('<h2>필수 장비</h2>', '<h2>Required Gear</h2>')
html = html.replace('<li>등산화 (미끄럼 방지)</li>', '<li>Hiking boots (with good grip)</li>')
html = html.replace('<li>무릎 보호대 (계단 많음)</li>', '<li>Knee braces (steep stairs)</li>')
html = html.replace('<li>트레킹 스틱 1쌍</li>', '<li>One pair of trekking poles</li>')
html = html.replace('<li>레인재킷 (날씨 변화 대비)</li>', '<li>Rain jacket (for sudden weather changes)</li>')
html = html.replace('<li>헤드램프</li>', '<li>Headlamp</li>')

html = html.replace('<h2>음식 &amp; 수분</h2>', '<h2>Food &amp; Hydration</h2>')
html = html.replace('<li>물 1.5L 이상 준비</li>', '<li>At least 1.5L of water</li>')
html = html.replace('<li>에너지바·초콜릿</li>', '<li>Energy bars / chocolate</li>')
html = html.replace('<li>소공원 매점 이용 가능</li>', '<li>Shops available at Sogongwon</li>')
html = html.replace('<li>정상부 취사 금지</li>', '<li>Cooking prohibited at the summit</li>')

html = html.replace('<h2>안전 수칙</h2>', '<h2>Safety Rules</h2>')
html = html.replace('<li>일몰 2시간 전 하산 완료</li>', '<li>Complete descent 2h before sunset</li>')
html = html.replace('<li>단독 산행 자제</li>', '<li>Avoid hiking alone</li>')
html = html.replace('<li>계단 구간 안전 손잡이 이용</li>', '<li>Hold on to safety railings on stairs</li>')
html = html.replace('<li>국립공원 탐방 예약 필수 확인</li>', '<li>Verify national park reservation</li>')

html = html.replace('<h2>교통 정보</h2>', '<h2>Transportation</h2>')
html = html.replace('<li>속초시내 → 설악동 시내버스 7-1번</li>', '<li>Sokcho City → Seorak-dong Local Bus No. 7-1</li>')
html = html.replace('<li>서울 동서울터미널 → 속초 고속버스</li>', '<li>Seoul Dong-Seoul Terminal → Sokcho Express Bus</li>')
html = html.replace('<li>설악동 주차장 유료 운영</li>', '<li>Paid parking at Seorak-dong Parking Lot</li>')
html = html.replace('<li>성수기 교통 혼잡 주의</li>', '<li>Beware of heavy traffic in peak seasons</li>')

html = html.replace('<h2>계절별 정보</h2>', '<h2>Seasonal Tips</h2>')
html = html.replace('<li>봄(4~5월): 철쭉 개화, 최고 탐방 시즌</li>', '<li>Spring (Apr-May): Azaleas bloom, peak hiking season</li>')
html = html.replace('<li>여름: 습도 높음, 계곡 탐방 추천</li>', '<li>Summer: High humidity, valley hikes recommended</li>')
html = html.replace('<li>가을(10월): 단풍 절정, 인파 집중</li>', '<li>Autumn (Oct): Peak autumn foliage, expect large crowds</li>')
html = html.replace('<li>겨울: 빙판 주의, 아이젠 필수</li>', '<li>Winter: Beware of icy trails, crampons mandatory</li>')

html = html.replace('<h2>유용한 앱</h2>', '<h2>Useful Apps</h2>')
html = html.replace('<li>국립공원 탐방예약 앱</li>', '<li>National Park Reservation App</li>')
html = html.replace('<li>산림청 스마트 산림재해 앱</li>', '<li>Smart Forest Disaster App</li>')
html = html.replace('<li>날씨 앱 (기상청 동네예보)</li>', '<li>Weather App (KMA forecast)</li>')
html = html.replace('<li>램블러 (GPS 트래킹)</li>', '<li>Ramblr (GPS Tracking)</li>')

# Route Map Section
html = html.replace('울산바위 코스 개념도', 'Ulsanbawi Course Map')
html = html.replace('등산로 개념도 (JS 로드 실패 시 표시)', 'Course Route Map (Fallback for JS load failure)')

# Checkpoints Detail List
html = html.replace('<h3>📍 세부 구간 가이드</h3>', '<h3>📍 Detailed Section Guide</h3>')
html = html.replace('소공원 탐방지원센터 출발', 'Sogongwon Park Ranger Office')
html = html.replace('해발 200m · 기점', 'Elevation 200m · Start Point')
html = html.replace(
    '설악동 소공원 탐방지원센터에서 시작합니다. 주차장 및 화장실 완비. 탐방안내소에서 지도를 받고 출발하세요. 신흥사 방향으로 걷기 시작합니다.',
    'Start from the Seorak-dong Sogongwon Ranger Office. Parking and restroom facilities available. Grab a map at the information desk. Walk towards Sinheungsa Temple.'
)
html = html.replace('소공원 → 신흥사 → 흔들바위', 'Sogongwon → Sinheungsa Temple → Heondeulbawi')
html = html.replace('약 1.5km · 40분 · 고도 ↑200m', 'Approx. 1.5km · 40 mins · Gain ↑200m')
html = html.replace(
    '완만한 평탄지 길을 따라 신흥사 일주문을 지나 계곡 소리를 들으며 걷습니다. 흔들바위(계조암)에 도착하면 큰 구형 바위를 흔들어보고 인증사진을 남겨보세요.',
    'Follow a flat, gentle trail past the Sinheungsa Temple gate, listening to the valley stream. Once at Heondeulbawi (Gyeojoam Hermitage), try pushing the giant spherical rock and take a photo.'
)

html = html.replace('흔들바위 → 울산바위 전망대', 'Heondeulbawi → Ulsanbawi Observatory')
html = html.replace('약 1km · 40분 · 고도 ↑300m', 'Approx. 1km · 40 mins · Gain ↑300m')
html = html.replace(
    '흔들바위부터 본격적인 오르막이 시작됩니다. 돌계단과 숲길이 번갈아 나오며, 경사가 점차 가팔라집니다. 중간 전망대에서 뒤돌아보면 외설악의 웅장한 침엽수림이 펼쳐집니다.',
    'The real ascent begins after Heondeulbawi. Stone steps alternate with forest trails as the slope grows steeper. Looking back from the intermediate observatory reveals the magnificent pine forests of Outer Seorak.'
)

html = html.replace('전망대 → 울산바위 정상 (철제 계단)', 'Observatory → Ulsanbawi Summit (Iron Stairs)')
html = html.replace('약 0.6km · 30분 · 고도 ↑173m', 'Approx. 0.6km · 30 mins · Gain ↑173m')
html = html.replace(
    '코스의 하이라이트이자 가장 힘든 구간입니다. 수직에 가까운 800여 개의 철제 계단이 바위 틈새를 따라 길게 이어집니다. 바람이 강하게 불 수 있으므로 난간을 꽉 잡고 주의해 오르세요.',
    'The highlight and most challenging section of the course. Over 800 nearly-vertical iron steps wind up through the rock crevices. Hold tightly to the railings as it can be very windy.'
)

html = html.replace('울산바위 정상 조망', 'Ulsanbawi Summit Panorama')
html = html.replace('해발 873m · 반환점', 'Elevation 873m · Halfway Point')
html = html.replace(
    '거대한 화강암 덩어리인 울산바위 정상에 서면 사방이 트여 동해바다, 속초시내, 그리고 설악산 최고의 비경인 대청봉과 공룡능선이 한눈에 조망됩니다.',
    'Standing on the giant granite blocks of Ulsanbawi Summit, enjoy panoramic views of the East Sea, Sokcho City, and Seoraksan\'s most scenic spots: Daecheongbong Peak and Dinosaur Ridge.'
)

html = html.replace('하산 시작 (역순 하산)', 'Descent (Return via Same Route)')
html = html.replace('약 1.6km · 50분 · 고도 ↓473m', 'Approx. 1.6km · 50 mins · Loss ↓473m')
html = html.replace(
    '정상에서 흔들바위까지 왔던 길을 따라 내려갑니다. 경사가 급하고 계단폭이 좁아 내려갈 때 무릎에 가해지는 충격에 주의하고 무릎 보호대를 착용하는 것이 좋습니다.',
    'Retrace your steps down from the summit to Heondeulbawi. Due to the steep slope and narrow steps, protect your knees and proceed slowly; wearing knee braces is recommended.'
)

html = html.replace('흔들바위 → 신흥사 → 소공원', 'Heondeulbawi → Sinheungsa Temple → Sogongwon')
html = html.replace('약 1.5km · 30분 · 고도 ↓200m', 'Approx. 1.5km · 30 mins · Loss ↓200m')
html = html.replace(
    '흔들바위부터는 평탄한 산책로 수준의 길입니다. 신흥사 경내를 둘러보거나 설악산 케이블카 타는 곳을 지나 소공원 입구로 복귀합니다.',
    'A gentle walk from Heondeulbawi onwards. Stroll through the Sinheungsa Temple grounds or pass by the cable car station as you return to the Sogongwon entrance.'
)

html = html.replace('소공원 도착 · 하산 완료', 'Descent Completed at Sogongwon')
html = html.replace('해발 200m · 종점', 'Elevation 200m · End Point')
html = html.replace(
    '소공원 주차장으로 돌아와 산행을 마무리합니다. 인근 설악동에는 다양한 식당과 카페가 있어 산행 후 식사 및 휴식이 편리합니다.',
    'Return to the Sogongwon Parking Lot to wrap up your hike. Local restaurants and cafes are nearby for dining and relaxation.'
)

# Table headers for Beginner
html = html.replace('<th>순번</th>', '<th>No.</th>')
html = html.replace('<th>지점명</th>', '<th>Checkpoint</th>')
html = html.replace('<th>해발고도</th>', '<th>Elevation</th>')
html = html.replace('<th>누적거리</th>', '<th>Distance</th>')
html = html.replace('<th>구간구분</th>', '<th>Type</th>')
html = html.replace('<th>주요 편의시설</th>', '<th>Facilities & Info</th>')

html = html.replace('<span class="badge badge-trailhead">출발점</span>', '<span class="badge badge-trailhead">Start</span>')
html = html.replace('<span class="badge badge-summit">정상</span>', '<span class="badge badge-summit">Summit</span>')
html = html.replace('<span class="badge badge-trailhead">종점</span>', '<span class="badge badge-trailhead">End</span>')
html = html.replace('<span class="badge badge-checkpoint">체크포인트</span>', '<span class="badge badge-checkpoint">Waypoint</span>')

html = html.replace('소공원 탐방지원센터', 'Sogongwon Ranger Office')
html = html.replace('주차·화장실·매점', 'Parking, Restrooms, Shops')
html = html.replace('신흥사 일주문', 'Sinheungsa Temple Gate')
html = html.replace('문화재안내판', 'Information Board')
html = html.replace('안락암', 'Anrakam Hermitage')
html = html.replace('약수터·화장실', 'Spring Water, Restrooms')
html = html.replace('흔들바위 (계조암)', 'Heondeulbawi (Gyeojoam)')
html = html.replace('화장실·안내소', 'Restrooms, Information Desk')
html = html.replace('울산바위 전망대', 'Ulsanbawi Observatory')
html = html.replace('포토존', 'Photo Zone')
html = html.replace('울산바위 정상', 'Ulsanbawi Summit')
html = html.replace('전망데크', 'Viewing Deck')
html = html.replace('소공원 귀환', 'Return to Sogongwon')
html = html.replace('식당·주차장', 'Restaurants, Parking')


# 7. Translate Course content - Intermediate Course (Osaek~Daecheongbong)
html = html.replace('📊 고도 프로파일 — 오색 대청봉 왕복', '📊 Elevation Profile — Osaek~Daecheongbong')
html = html.replace('설악산 최고봉인 대청봉(1,708m)을 가장 빠르게 오르는 최단 코스입니다.', 'This is the shortest and fastest route to Daecheongbong Peak (1,708m), the highest point of Seoraksan.')
html = html.replace('오색 탐방지원센터에서 출발해 편도 5km 구간 동안 고도를 무려 1,500m나 끌어올려야 하는 극악의 경사도를 자랑합니다.', 'Starting from the Osaek Ranger Office, it gains an intense 1,500m of elevation over a single 5km stretch.')
html = html.replace('조망이 거의 없고 돌계단과 가파른 숲길만 이어져 지루하고 힘들지만, 대청봉 정상에 올라서면 피로가 씻은 듯이 날아가는 감동을 줍니다.', 'The trail offers few views as it climbs steeply through dense forests and stone steps, but reaching the summit brings unforgettable views.')

html = html.replace('<li>등산화 (방수·미끄럼 방지)</li>', '<li>Waterproof, slip-resistant hiking boots</li>')
html = html.replace('<li>무릎 보호대 (필수)</li>', '<li>Knee braces (essential)</li>')
html = html.replace('<li>트레킹 스틱 2개</li>', '<li>Two trekking poles</li>')
html = html.replace('<li>방한·방풍 재킷</li>', '<li>Insulated, windproof jacket</li>')
html = html.replace('<li>헤드램프·여벌 배터리</li>', '<li>Headlamp with spare batteries</li>')

html = html.replace('<li>물 2L 이상</li>', '<li>At least 2L of water</li>')
html = html.replace('<li>에너지바·도시락</li>', '<li>Energy bars / packed lunch</li>')
html = html.replace('<li>중청대피소 컵라면 판매</li>', '<li>Cup noodles sold at Jungcheong Shelter</li>')
html = html.replace('<li>정상부 기온 급강하 대비 따뜻한 음식</li>', '<li>Warm food for sub-zero summit temperatures</li>')

html = html.replace('<li>오전 일찍 출발 (새벽 4~5시)</li>', '<li>Start early morning (4-5 AM)</li>')
html = html.replace('<li>오후 1시 이후 입산 자제</li>', '<li>Avoid starting after 1 PM</li>')
html = html.replace('<li>안개·비 시 바위 미끄럼 극도 주의</li>', '<li>Extreme caution on slippery rocks when wet</li>')
html = html.replace('<li>정상 기상 급변 대비 여벌 옷 필수</li>', '<li>Extra layers mandatory for summit microclimate</li>')

html = html.replace('<li>양양 시외버스터미널 → 오색 버스</li>', '<li>Yangyang Bus Terminal → Osaek Local Bus</li>')
html = html.replace('<li>서울 동서울터미널 → 양양 고속버스</li>', '<li>Seoul Dong-Seoul Terminal → Yangyang Bus</li>')
html = html.replace('<li>오색 주차장 유료 운영</li>', '<li>Paid parking at Osaek Parking Lot</li>')

html = html.replace('<h2>정상 환경</h2>', '<h2>Summit Conditions</h2>')
html = html.replace('<li>대청봉 평균 기온: 여름 10°C 내외</li>', '<li>Average summer temperature: ~10°C</li>')
html = html.replace('<li>안개 발생 빈번, 가시거리 주의</li>', '<li>Frequent fog, expect low visibility</li>')
html = html.replace('<li>강풍 빈발 — 모자 분실 주의</li>', '<li>Strong winds — secure your hats</li>')
html = html.replace('<li>겨울 아이젠·게이터 필수</li>', '<li>Crampons and gaiters mandatory in winter</li>')

html = html.replace('<h2>사전 준비</h2>', '<h2>Pre-hike Checklist</h2>')
html = html.replace('<li>기상청 산악기상 예보 체크</li>', '<li>Check Mountain Weather forecast</li>')
html = html.replace('<li>비상 연락처 보호자에게 공유</li>', '<li>Share emergency contacts with family</li>')
html = html.replace('<li>체력 훈련 최소 2~3개월 권장</li>', '<li>At least 2-3 months of training recommended</li>')

html = html.replace('오색 대청봉 코스 개념도', 'Osaek~Daecheongbong Course Map')

# Section guide Osaek
html = html.replace('오색 탐방지원센터 출발', 'Osaek Ranger Office')
html = html.replace('해발 250m · 기점', 'Elevation 250m · Start Point')
html = html.replace(
    '오색 탐방지원센터 입구를 지나 가파른 돌계단으로 바로 진입합니다. 초반부터 강도 높은 오르막이므로 숨고르기를 하며 천천히 출발합니다.',
    'Pass through the Osaek Ranger Office and immediately enter the steep stone stairs. Pace yourself right from the start.'
)
html = html.replace('오색 → 제1쉼터 → 제2쉼터', 'Osaek → 1st Shelter → 2nd Shelter')
html = html.replace('약 2.5km · 1시간 30분 · 고도 ↑600m', 'Approx. 2.5km · 1h 30m · Gain ↑600m')
html = html.replace(
    '조망이 없는 울창한 숲속 급경사를 오릅니다. 제1쉼터와 제2쉼터에서 수분을 보충하고 충분히 휴식하세요. 경사도가 낮아지지 않는 마의 구간입니다.',
    'Climb a steep incline through dense forest with limited views. Take rest and hydrate at the 1st and 2nd shelters. The slope remains unforgiving throughout.'
)
html = html.replace('제2쉼터 → 설악폭포 → 삼거리', '2nd Shelter → Seorak Falls → Junction')
html = html.replace('약 1.5km · 1시간 10분 · 고도 ↑500m', 'Approx. 1.5km · 1h 10m · Gain ↑500m')
html = html.replace(
    '삼거리 이정표가 나오기 전까지 끊임없는 가파른 나무 데크 계단과 너덜지대가 이어집니다. 대청봉 정상부가 가까워질수록 기온이 급격히 내려가니 외투를 준비하세요.',
    'Endless wooden deck stairs and rocky terrain continue until the junction. Temperatures drop rapidly near the summit, so have your jacket ready.'
)
html = html.replace('설악 삼거리 → 대청봉 정상', 'Seorak Junction → Daecheongbong Summit')
html = html.replace('약 1km · 40분 · 고도 ↑358m', 'Approx. 1km · 40 mins · Gain ↑358m')
html = html.replace(
    '가파른 숲을 벗어나 관목대로 진입하며 하늘이 열립니다. 바람이 매우 강해지며 대청봉 정상석이 시야에 들어옵니다. 한계령 삼거리에서 합류하는 등산객들과 만납니다.',
    'As you exit the dense forest and enter the alpine shrub zone, the sky opens up. The wind grows strong as the Daecheongbong summit stone comes into view.'
)
html = html.replace('대청봉 정상 정복', 'Daecheongbong Peak')
html = html.replace('해발 1,708m · 반환점', 'Elevation 1,708m · Halfway Point')
html = html.replace(
    '남한에서 세 번째로 높은 대청봉 정상석 옆에서 기념 사진을 촬영합니다. 날씨가 맑으면 백담사 방면 내설악과 공룡능선, 속초 앞바다까지 거대한 파노라마가 한눈에 들어옵니다.',
    'Take a photo next to the summit stone of Daecheongbong, the third highest peak in South Korea. On clear days, enjoy views of Inner Seorak, Dinosaur Ridge, and the East Sea.'
)
html = html.replace('대청봉 → 오색 회환 (하산)', 'Daecheongbong → Return to Osaek')
html = html.replace('약 5km · 3시간 · 고도 ↓1,458m', 'Approx. 5km · 3 hours · Loss ↓1,458m')
html = html.replace(
    '올라왔던 가파른 경사로를 그대로 내려갑니다. 경사가 매우 심해 미끄러지기 쉬우므로 스틱을 적극 활용하고, 하산 속도를 늦추어 발목과 무릎을 보호하세요.',
    'Descend the steep path back to Osaek. Due to the high risk of slipping, use trekking poles actively and descend slowly to protect your knees and ankles.'
)

# Table Osaek
html = html.replace('오색 탐방지원센터', 'Osaek Ranger Office')
html = html.replace('제1쉼터', '1st Shelter')
html = html.replace('쉼터 의자', 'Benches')
html = html.replace('설악폭포', 'Seorak Falls')
html = html.replace('안전쉼터', 'Emergency Shelter')
html = html.replace('제2쉼터', '2nd Shelter')
html = html.replace('설악 삼거리', 'Seorak Junction')
html = html.replace('대청봉 대피소 이정표', 'Shelter Signpost')
html = html.replace('대청봉 (정상석)', 'Daecheongbong (Summit Stone)')
html = html.replace('오색 귀환', 'Return to Osaek')


# 8. Translate Course content - Advanced Course (Traverse)
html = html.replace('📊 고도 프로파일 — 내외설악 관통 종주 (백담사→대청봉→소공원)', '📊 Elevation Profile — Inner-Outer Traverse (Baekdamsa → Daecheongbong → Sogongwon)')
html = html.replace('인제 백담계곡에서 시작해 내설악의 수려한 계곡을 따라 대청봉을 정복하고, 외설악의 천불동계곡으로 하산하는 대표적인 1박 2일 종주 코스입니다.', 'This classic 2-day traverse starts from Baekdamsa Temple in Inje, climbs through the serene valleys of Inner Seorak, conquers Daecheongbong Peak, and descends via Cheonbuldong Valley.')
html = html.replace('수려한 폭포와 기암괴석이 끝없이 이어지며, 소청대피소에서 밤을 보내며 은하수와 산속 일출을 경험하는 낭만이 가득한 명품 등산로입니다.', 'Pass majestic waterfalls and dramatic granite cliffs, spend the night at Socheong Shelter, and experience stunning starry skies and mountain sunrises.')

html = html.replace('<li>등산화 (방수·발목 지지)</li>', '<li>Waterproof hiking boots (with ankle support)</li>')
html = html.replace('<li>침낭 (대피소용)</li>', '<li>Sleeping bag (for shelter)</li>')
html = html.replace('<li>헤드램프 + 여벌 건전지</li>', '<li>Headlamp with spare batteries</li>')
html = html.replace('<li>우비·방풍재킷</li>', '<li>Raincoat / windbreaker</li>')

html = html.replace('<li>물 3L (중간 보충 가능)</li>', '<li>3L of water (can refill at shelters)</li>')
html = html.replace('<li>간편식 2일분 (건조식품·에너지바)</li>', '<li>2 days of freeze-dried food / energy bars</li>')
html = html.replace('<li>대피소 컵라면·음료 구매 가능</li>', '<li>Cup noodles/drinks sold at shelters</li>')
html = html.replace('<li>고열량 행동식 충분히 준비</li>', '<li>Ample high-calorie trail snacks</li>')

html = html.replace('<h2>대피소 예약</h2>', '<h2>Shelter Reservations</h2>')
html = html.replace('<li>소청대피소 필수 예약</li>', '<li>Reservations mandatory for Socheong Shelter</li>')
html = html.replace('<li>국립공원 예약 시스템(knps.or.kr)</li>', '<li>Korea National Park System (knps.or.kr)</li>')
html = html.replace('<li>성수기 2~3개월 전 예약 필요</li>', '<li>Book 2-3 months in advance for peak season</li>')
html = html.replace('<li>수렴동대피소 (선택 전진기지)</li>', '<li>Suryeomdong Shelter (optional stopover)</li>')

html = html.replace('<li>입산 통제 시간 엄수</li>', '<li>Observe strict park entry cutoff times</li>')
html = html.replace('<li>공룡능선 입구: 4~10월 오후 1시, 동절기 오전 10시 전 도착</li>', '<li>Dinosaur Ridge Gate: Reach by 1 PM (Apr-Oct) or 10 AM (Winter)</li>')
html = html.replace('<li>기상 악화 시 즉시 하산</li>', '<li>Descend immediately in case of severe weather</li>')
html = html.replace('<li>1인 산행 금지 (2인 이상 팀)</li>', '<li>No solo hiking (minimum team of 2)</li>')

html = html.replace('<li>용대리(인제) → 백담사 셔틀버스</li>', '<li>Yongdaeri (Inje) → Baekdamsa Shuttle Bus</li>')
html = html.replace('<li>서울 → 인제 고속버스</li>', '<li>Seoul → Inje Express Bus</li>')
html = html.replace('<li>소공원(속초) → 서울 고속버스</li>', '<li>Sogongwon (Sokcho) → Seoul Express Bus</li>')
html = html.replace('<li>출발/도착지 분리 — 교통 계획 필수</li>', '<li>Point-to-point hike — plan transport carefully</li>')

html = html.replace('<h2>체력 준비</h2>', '<h2>Physical Training</h2>')
html = html.replace('<li>최소 6개월 등산 훈련 권장</li>', '<li>At least 6 months of conditioning recommended</li>')
html = html.replace('<li>10kg 이상 배낭 훈련 필수</li>', '<li>Training with a 10kg+ backpack is essential</li>')
html = html.replace('<li>10km 이상 산행 5회 이상 경험</li>', '<li>Complete at least 5 hikes over 10km</li>')
html = html.replace('<li>중급 코스 사전 완주 후 도전</li>', '<li>Ensure you have completed intermediate courses first</li>')

html = html.replace('내외설악 관통 종주 코스 개념도', 'Inner-Outer Traverse Course Map')

# Section guide Traverse
html = html.replace('📅 1일차: 용대리 → 백담사 → 수렴동 → 소청대피소 (약 13km, 5~6시간)', '📅 Day 1: Yongdaeri → Baekdamsa → Suryeomdong → Socheong Shelter (Approx. 13km, 5-6h)')
html = html.replace(
    '용대리 마을에서 백담사 셔틀버스를 타고 출발합니다. 백담사계곡의 맑은 물소리를 들으며 평탄한 길로 시작합니다. 수렴동대피소를 지나 봉정암까지 급경사 계단(깔딱고개)이 이어져 마지막 체력을 안배해야 합니다. 봉정암을 지나 소청대피소에 도착해 첫날 일정을 마무리하고 휴식합니다.',
    'Take the shuttle bus from Yongdaeri to Baekdamsa Temple. Start with a flat trail along the clear waters of Baekdam Valley. Pass Suryeomdong Shelter, then tackle the extremely steep steps up to Bongjeongam Hermitage. Continue past Bongjeongam to reach Socheong Shelter to rest for the night.'
)
html = html.replace('📅 2일차: 소청대피소 → 대청봉 → 천불동계곡 → 소공원 (약 11km, 6~7시간)', '📅 Day 2: Socheong Shelter → Daecheongbong → Cheonbuldong Valley → Sogongwon (Approx. 11km, 6-7h)')
html = html.replace(
    '이른 새벽 대청봉 정상에 올라 일출을 감상한 뒤, 외설악 방향으로 본격적인 하산을 진행합니다. 중청, 희운각을 지나 비선대까지 이어지는 천불동계곡은 기암괴석과 은빛 물줄기의 폭포들이 끝없이 이어지는 절경을 이룹니다. 소공원에 도달해 대여정을 마무리합니다.',
    'Climb to Daecheongbong summit early in the morning for sunrise, then begin your descent towards Outer Seorak. Descend through Jungcheong and Huiungak to Cheonbuldong Valley, featuring breathtaking granite cliffs and emerald waterfalls. Reach Sogongwon to complete your grand trek.'
)

html = html.replace('백담사 탐방로 시작', 'Baekdamsa Trailhead')
html = html.replace('해발 450m · 기점', 'Elevation 450m · Start Point')
html = html.replace(
    '백담사 셔틀버스 정류장에서 하차하여 일주문을 지나 계곡 평탄한 산책로를 따라 걷기 시작합니다. 계곡 물길을 가로지르는 수많은 돌탑들이 장관을 이룹니다.',
    'Get off the shuttle bus at Baekdamsa Temple, pass the gate, and walk along the flat valley trail. Enjoy the countless stone pagodas built along the riverbed.'
)
html = html.replace('백담사 → 영시암 → 수렴동대피소', 'Baekdamsa → Yeongsiam → Suryeomdong Shelter')
html = html.replace('약 4.7km · 1시간 30분 · 고도 ↑100m', 'Approx. 4.7km · 1h 30m · Gain ↑100m')
html = html.replace(
    '계곡을 옆에 두고 숲길 산책 수준의 완만한 길이 영시암을 거쳐 수렴동대피소까지 이어집니다. 수렴동대피소에서 첫 휴식을 취하며 식수를 보충합니다.',
    'A gentle forest walk along the stream leads past Yeongsiam Hermitage to Suryeomdong Shelter. Take your first rest here and refill water.'
)
html = html.replace('수렴동대피소 → 구곡담계곡 → 쌍용폭포', 'Suryeomdong Shelter -> Gugokdam Valley -> Ssangyong Falls')
html = html.replace('약 4.5km · 2시간 · 고도 ↑300m', 'Approx. 4.5km · 2 hours · Gain ↑300m')
html = html.replace(
    '내설악 최고의 비경인 구곡담계곡에 접어듭니다. 수많은 용소와 폭포(관음폭포, 쌍용폭포)를 감상하며 테크 길과 돌길을 차례로 걷습니다. 완만하던 고도가 점점 올라갑니다.',
    'Enter Gugokdam Valley, one of Inner Seorak\'s most scenic areas. Enjoy beautiful plunge pools and waterfalls (Gwaneum and Ssangyong Falls) as you hike along boardwalks and rocky trails.'
)
html = html.replace('쌍용폭포 → 봉정암 (깔딱고개)', 'Ssangyong Falls → Bongjeongam (Steep Incline)')
html = html.replace('약 1.8km · 1시간 20분 · 고도 ↑600m', 'Approx. 1.8km · 1h 20m · Gain ↑600m')
html = html.replace(
    '봉정암으로 향하는 마지막 1km 구간은 경사가 45도에 육박하는 급경사 데크 계단과 바윗길(깔딱고개)입니다. 체력이 급격히 소모되므로 호흡을 고르며 매우 천천히 올라야 합니다.',
    'The final 1km up to Bongjeongam is an extremely steep ascent (near 45-degree slope) up wooden stairs and rocks. Pace yourself slowly as it is very demanding.'
)
html = html.replace('봉정암 → 소청봉 → 소청대피소', 'Bongjeongam → Socheongbong → Socheong Shelter')
html = html.replace('약 1km · 40분 · 고도 ↑200m', 'Approx. 1km · 40 mins · Gain ↑200m')
html = html.replace(
    '우리나라에서 가장 높은 사찰인 봉정암(1,244m)에서 기도를 올리거나 휴식한 뒤, 소청봉을 향해 숲길을 더 올라갑니다. 소청 삼거리 아래에 있는 소청대피소에 도착해 숙박을 준비합니다.',
    'Rest at Bongjeongam Hermitage (1,244m), the highest temple in Korea, then continue up the forest path towards Socheongbong Peak. Head to Socheong Shelter to check in for the night.'
)
html = html.replace('소청대피소 → 중청 → 대청봉 정상 (일출)', 'Socheong Shelter → Jungcheong → Daecheongbong (Sunrise)')
html = html.replace('약 1.5km · 1시간 · 고도 ↑330m', 'Approx. 1.5km · 1 hour · Gain ↑330m')
html = html.replace(
    '새벽 4시경 대피소를 출발하여 랜턴을 켜고 중청대피소를 경유해 대청봉에 올라 일출을 감상합니다. 새벽 정상은 한여름에도 패딩이 필요할 정도로 극도로 춥습니다.',
    'Depart around 4 AM with headlamps, pass Jungcheong Shelter, and reach the Daecheongbong summit for sunrise. Pack an insulated jacket, as the summit is freezing even in summer.'
)
html = html.replace('대청봉 → 희운각대피소', 'Daecheongbong → Huiungak Shelter')
html = html.replace('약 2.5km · 1시간 30분 · 고도 ↓650m', 'Approx. 2.5km · 1h 30m · Loss ↓650m')
html = html.replace(
    '대청봉에서 다시 중청 삼거리로 내려와 희운각대피소 방향 경사지를 급하게 내려갑니다. 바윗길이 매우 거칠어 무릎 부상에 극도로 유의해야 하는 하산 난코스입니다.',
    'Descend to Jungcheong junction and follow the steep trail down to Huiungak Shelter. Watch your knees on the rough rocky descent.'
)
html = html.replace('희운각대피소 → 천불동계곡 → 양폭대피소', 'Huiungak Shelter → Cheonbuldong Valley → Yangpok Shelter')
html = html.replace('약 2km · 1시간 20분 · 고도 ↓350m', 'Approx. 2km · 1h 20m · Loss ↓350m')
html = html.replace(
    '희운각대피소에서 간단히 식사 후 천불동계곡에 진입합니다. 양쪽으로 거대한 화강암 침봉들이 하늘을 찌르고 계곡을 가로지르는 철제 데크를 따라 폭포(천당폭포)를 지나 양폭대피소에 닿습니다.',
    'Have a quick meal at Huiungak Shelter, then enter Cheonbuldong Valley. Walk along iron boardwalks flanked by towering granite peaks, passing Cheondang Falls to reach Yangpok Shelter.'
)
html = html.replace('양폭대피소 → 비선대 → 신흥사 → 소공원', 'Yangpok Shelter → Biseondae → Sinheungsa → Sogongwon')
html = html.replace('약 5km · 1시간 40분 · 고도 ↓300m', 'Approx. 5km · 1h 40m · Loss ↓300m')
html = html.replace(
    '비선대(명승 제1호)를 지나 신흥사 경내를 통해 설악동 소공원으로 마무리합니다. 완만한 탐방로로 피로한 다리를 달래며 여유롭게 걸을 수 있습니다. 소공원에서 속초 시내버스로 이동하세요.',
    'Pass through Biseondae (Scenic Site No. 1) and Sinheungsa Temple to finish at Seorak-dong Sogongwon. The trail is gentle here, letting you relax your legs. Take a local bus from Sogongwon.'
)
html = html.replace('<div class="tip-box"><svg class="icon-svg"><use href="../assets/icons/icons.svg#icon-tip"></use></svg> 소공원 도착 후 설악동 식당에서 식사. 속초 시내 해물탕, 물회 추천!</div>',
                     '<div class="tip-box"><svg class="icon-svg"><use href="../assets/icons/icons.svg#icon-tip"></use></svg> Arrive at Sogongwon. Recommended dishes in Sokcho: Haemultang (seafood stew) or Mulhoe (cold raw fish soup)!</div>')

# Table Traverse
html = html.replace('백담사 탐방지원센터', 'Baekdamsa Ranger Office')
html = html.replace('영시암', 'Yeongsiam Hermitage')
html = html.replace('식수터', 'Spring Water')
html = html.replace('수렴동대피소', 'Suryeomdong Shelter')
html = html.replace('대피소·매점', 'Shelter, Shop')
html = html.replace('봉정암 사찰', 'Bongjeongam Temple')
html = html.replace('화장실·식수', 'Restrooms, Water')
html = html.replace('소청대피소 (숙박)', 'Socheong Shelter (Overnight)')
html = html.replace('중청대피소', 'Jungcheong Shelter')
html = html.replace('희운각대피소', 'Huiungak Shelter')
html = html.replace('양폭대피소', 'Yangpok Shelter')
html = html.replace('대피소 무선통신', 'Emergency Radio')
html = html.replace('비선대', 'Biseondae Rock')
html = html.replace('안내판', 'Information Board')
html = html.replace('소공원 종점', 'Sogongwon Terminal')

html = html.replace('1일', 'Day 1')
html = html.replace('2일', 'Day 2')


# 9. Translate Navigation menu sidebar
html = html.replace('<span class="nav-title">가이드 목차</span>', '<span class="nav-title">Playbook Directory</span>')
html = html.replace('설악산 국립공원', 'Seoraksan National Park')
html = html.replace('코스 비교', 'Course Comparison')
html = html.replace('등산 가이드', 'Hiking Guides')
html = html.replace('준비물 &amp; 안전', 'Gear &amp; Safety')
html = html.replace('대중교통 안내', 'Transportation')

# Footer
html = html.replace('설악산 국립공원 등산 플레이북', 'Seoraksan National Park Hiking Playbook')
html = html.replace('본 웹사이트에 수록된 정보는 등산로 통제 및 실시간 기상 상태에 따라 달라질 수 있으므로, 출발 전 국립공원공단 등의 공식 안내를 반드시 확인하시기 바랍니다.',
                    'The information on this website is subject to trail closures and real-time weather conditions. Please check official advisories (such as the Korea National Park Service) before starting your hike.')

# 10. Translate SVG Text Nodes in diagrams
# Beginner SVG
html = html.replace('<text fill="var(--color-text-muted)" font-family="Satoshi,sans-serif" font-size="11" x="5" y="155">소공원 200m</text>',
                    '<text fill="var(--color-text-muted)" font-family="Satoshi,sans-serif" font-size="11" x="5" y="155">Sogongwon 200m</text>')
html = html.replace('<text fill="var(--color-text-muted)" font-family="Satoshi,sans-serif" font-size="11" x="145" y="125">흔들바위 380m</text>',
                    '<text fill="var(--color-text-muted)" font-family="Satoshi,sans-serif" font-size="11" x="145" y="125">Heondeulbawi 380m</text>')
html = html.replace('<text fill="var(--color-text-muted)" font-family="Satoshi,sans-serif" font-size="11" x="290" y="45">울산바위 873m</text>',
                    '<text fill="var(--color-text-muted)" font-family="Satoshi,sans-serif" font-size="11" x="290" y="45">Ulsanbawi 873m</text>')

html = html.replace('🅿 소공원', '🅿 Sogongwon')
html = html.replace('흔들바위', 'Heondeulbawi')
html = html.replace('울산바위 (정상)', 'Ulsanbawi (Summit)')
html = html.replace('소공원 도착', 'Arrive Sogongwon')

# Intermediate SVG
html = html.replace('<text fill="var(--color-text-muted)" font-family="Satoshi,sans-serif" font-size="11" x="5" y="155">오색 250m</text>',
                    '<text fill="var(--color-text-muted)" font-family="Satoshi,sans-serif" font-size="11" x="5" y="155">Osaek 250m</text>')
html = html.replace('<text fill="var(--color-text-muted)" font-family="Satoshi,sans-serif" font-size="11" x="145" y="110">설악폭포 900m</text>',
                    '<text fill="var(--color-text-muted)" font-family="Satoshi,sans-serif" font-size="11" x="145" y="110">Seorak Falls 900m</text>')
html = html.replace('<text fill="var(--color-text-muted)" font-family="Satoshi,sans-serif" font-size="11" x="290" y="40">대청봉 1708m</text>',
                    '<text fill="var(--color-text-muted)" font-family="Satoshi,sans-serif" font-size="11" x="290" y="40">Daecheongbong 1708m</text>')

html = html.replace('🅿 오색', '🅿 Osaek')
html = html.replace('설악폭포', 'Seorak Falls')
html = html.replace('대청봉 (정상)', 'Daecheongbong (Summit)')
html = html.replace('오색 도착', 'Arrive Osaek')

# Advanced SVG
html = html.replace('<text fill="var(--color-text-muted)" font-family="Satoshi,sans-serif" font-size="10" x="5" y="130">백담사</text>',
                    '<text fill="var(--color-text-muted)" font-family="Satoshi,sans-serif" font-size="10" x="5" y="130">Baekdamsa</text>')
html = html.replace('<text fill="var(--color-text-muted)" font-family="Satoshi,sans-serif" font-size="10" x="5" y="142">450m</text>',
                    '<text fill="var(--color-text-muted)" font-family="Satoshi,sans-serif" font-size="10" x="5" y="142">450m</text>')

html = html.replace('<text fill="var(--color-text-muted)" font-family="Satoshi,sans-serif" font-size="10" x="150" y="125">수렴동</text>',
                    '<text fill="var(--color-text-muted)" font-family="Satoshi,sans-serif" font-size="10" x="150" y="125">Suryeomdong</text>')
html = html.replace('<text fill="var(--color-text-muted)" font-family="Satoshi,sans-serif" font-size="10" x="150" y="137">550m</text>',
                    '<text fill="var(--color-text-muted)" font-family="Satoshi,sans-serif" font-size="10" x="150" y="137">550m</text>')

html = html.replace('<text fill="var(--color-text-muted)" font-family="Satoshi,sans-serif" font-size="10" x="380" y="70">소청</text>',
                    '<text fill="var(--color-text-muted)" font-family="Satoshi,sans-serif" font-size="10" x="380" y="70">Socheong</text>')
html = html.replace('<text fill="var(--color-text-muted)" font-family="Satoshi,sans-serif" font-size="10" x="380" y="82">1575m</text>',
                    '<text fill="var(--color-text-muted)" font-family="Satoshi,sans-serif" font-size="10" x="380" y="82">1575m</text>')

html = html.replace('<text fill="var(--color-text-muted)" font-family="Satoshi,sans-serif" font-size="10" x="480" y="32">대청봉</text>',
                    '<text fill="var(--color-text-muted)" font-family="Satoshi,sans-serif" font-size="10" x="480" y="32">Daecheongbong</text>')
html = html.replace('<text fill="var(--color-text-muted)" font-family="Satoshi,sans-serif" font-size="10" x="480" y="44">1708m</text>',
                    '<text fill="var(--color-text-muted)" font-family="Satoshi,sans-serif" font-size="10" x="480" y="44">1708m</text>')

html = html.replace('<text fill="var(--color-text-muted)" font-family="Satoshi,sans-serif" font-size="10" x="590" y="90">희운각</text>',
                    '<text fill="var(--color-text-muted)" font-family="Satoshi,sans-serif" font-size="10" x="590" y="90">Huiungak</text>')
html = html.replace('<text fill="var(--color-text-muted)" font-family="Satoshi,sans-serif" font-size="10" x="590" y="102">1040m</text>',
                    '<text fill="var(--color-text-muted)" font-family="Satoshi,sans-serif" font-size="10" x="590" y="102">1040m</text>')

html = html.replace('<text fill="var(--color-text-muted)" font-family="Satoshi,sans-serif" font-size="10" x="730" y="115">비선대</text>',
                    '<text fill="var(--color-text-muted)" font-family="Satoshi,sans-serif" font-size="10" x="730" y="115">Biseondae</text>')
html = html.replace('<text fill="var(--color-text-muted)" font-family="Satoshi,sans-serif" font-size="10" x="730" y="127">300m</text>',
                    '<text fill="var(--color-text-muted)" font-family="Satoshi,sans-serif" font-size="10" x="730" y="127">300m</text>')

html = html.replace('<text fill="var(--color-text-muted)" font-family="Satoshi,sans-serif" font-size="10" text-anchor="end" x="875" y="147">소공원</text>',
                    '<text fill="var(--color-text-muted)" font-family="Satoshi,sans-serif" font-size="10" text-anchor="end" x="875" y="147">Sogongwon</text>')
html = html.replace('<text fill="var(--color-text-muted)" font-family="Satoshi,sans-serif" font-size="10" text-anchor="end" x="875" y="159">200m</text>',
                    '<text fill="var(--color-text-muted)" font-family="Satoshi,sans-serif" font-size="10" text-anchor="end" x="875" y="159">200m</text>')

html = html.replace('1일차 (백담사→소청)', 'Day 1 (Baekdamsa → Socheong)')
html = html.replace('2일차 (대청봉→소공원)', 'Day 2 (Daecheongbong → Sogongwon)')
html = html.replace('백담사', 'Baekdamsa')
html = html.replace('수렴동', 'Suryeomdong')
html = html.replace('소청', 'Socheong')
html = html.replace('대청봉', 'Daecheongbong')
html = html.replace('희운각', 'Huiungak')
html = html.replace('비선대', 'Biseondae')
html = html.replace('소공원', 'Sogongwon')

# Additional diagram text
html = html.replace('소공원 P', 'Sogongwon P')
html = html.replace('흔들바위', 'Heondeulbawi')
html = html.replace('울산바위 873m', 'Ulsanbawi 873m')
html = html.replace('소공원(설악동) P →', 'Sogongwon (Seorak-dong) P →')
html = html.replace('양폭', 'Yangpok')

with open('en/seoraksan-playbook.html', 'w', encoding='utf-8') as f:
    f.write(html)

print("Generated en/seoraksan-playbook.html successfully!")
